all:
	cyclone sum-no-sync.scm && time ./sum-no-sync
	cyclone sum-mutex.scm && time ./sum-mutex
	cyclone sum-spin-lock.scm && time ./sum-spin-lock
	cyclone sum-atomic-fxbox.scm && time ./sum-atomic-fxbox
